name: Flutter Build APK (Shuaib Jaame App Final)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Enable Android SDK Licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Shuaib_Jaame_App_Final_v1
          path: build/app/outputs/flutter-apk/app-release.apk
